# Generated by Django 3.2.15 on 2022-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
