# Generated by Django 4.1.1 on 2022-09-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220921_1850"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "uuid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("firstOption", models.CharField(max_length=255)),
                ("secondOption", models.CharField(max_length=255)),
                ("firstOptionVoteCount", models.IntegerField(default=0)),
                ("secondOptionVoteCount", models.IntegerField(default=0)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
